#!/bin/bash
# ==============================================================================
#  Title:         psychopy_linux_installer
#  Description:   This script installs PsychoPy with specified versions of
#                 Python, wxPython, and optional packages.
#  Author:        Lukas Wiertz
#  Date:          2024-11-02
#  Version:       1.2.5
#  License:       GNU General Public License v3.0
# ==============================================================================

show_help() {
    cat << EOF
Usage: ./psychopy_linux_installer [options]
Options:
  --psychopy-version=VERSION                    Specify PsychoPy version (default: latest).
  --python-version=3.8|3.9|3.10                 Specify Python version (default: 3.10).
  --wxpython-version=VERSION                    Specify wxPython version (default: 4.2.2).
  --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading.
  --install-dir=DIR                             Specify installation directory (default: "$HOME").
  --no-versioned-install-dir                    Install directly into install-dir without creating a versioned subdirectory. Requires --install-dir.
  --additional-packages=PACKAGES                Specify additional pip packages to install. Format: package1==version,package2. No version is latest.
  --sudo-mode=[ask|auto|error|continue|force]   Control sudo usage. ask: confirm, auto: auto-confirm, error: exit if sudo needed, continue: continue without sudo, force: use sudo directly.
  --disable-shortcut                            Disable desktop shortcut creation.
  --disable-path                                Disable adding psychopy to system path.
  -f, --force                                   Force overwrite of existing installation directory.
  -v, --verbose                                 Enable verbose output.
  -h, --help                                    Show this help message.
EOF
}

# Logging function for verbose output
log() {
    if [ "$verbose" = true ]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# Function to print log messages with timestamp
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
}

# Wrapper function to handle sudo requests and permissions dynamically
sudo_wrapper() {
    local error_output exit_code
    local command=("$@")
    local is_pkg_manager_command=false

    needs_sudo() {
        local exit_code=$1
        local error_output=$2

        case $exit_code in
            0) return 1 ;;  
            1|2|5|10|13|77|100|126|127) return 0 ;;
            *)
                log_message "Warning: Unhandled exit code $exit_code. Error output: $error_output. Trying to continue ..."
                return 1 ;;
        esac
    }

    handle_sudo_request() {
        local command=("$@")
        local response

        case "$sudo_mode" in
            ask)
                if $is_pkg_manager_command; then
                    log_message "Warning: Command '${command[*]}' failed with '${error_output}'."
                    read -r -p "Retry with sudo for this and all future $pkg_manager commands(r), continue(c), quit(q), or auto sudo when needed(a)? [r/c/q/a] " response
                else
                    log_message "Warning: Command '${command[*]}' failed with '${error_output}'."
                    read -r -p "Retry with sudo(r), continue without sudo(c), quit(q), or auto sudo when needed(a)? [r/c/q/a] " response
                fi

                case "$response" in
                    [Rr])
                        if $is_pkg_manager_command; then
                            pkg_manager_permission=true
                        fi
                        log_message "Info: Retrying ${command[*]} with sudo ..."
                        log sudo "${command[@]}"
                        ;;
                    [Cc])
                        ;;
                    [aA])
                        log_message "Info: Retrying ${command[*]} with sudo and setting sudo-mode=auto ..."
                        log sudo "${command[@]}"
                        sudo_mode=auto
                        ;;
                    *)
                        log_message "Info: Exiting."
                        exit 1
                        ;;
                esac
                ;;
            auto)
                if $is_pkg_manager_command; then
                    pkg_manager_permission=true
                fi
                log log_message "Warning: Command '${command[*]}' failed with: '${error_output}'. Using sudo..."
                log sudo "${command[@]}"
                ;;
            continue)
                log_message "Warning: Command '${command[*]}' failed with: '${error_output}'. Continuing without sudo..."
                ;;
            error)
                log_message "Error: Command '${command[*]}' failed with '${error_output}'. Sudo is required, but mode is set to 'error'."
                exit 1
                ;;
        esac
    }

    is_pkg_manager_command=$([ "$1" == "$pkg_manager" ] && echo true || echo false)

    if [[ "$sudo_mode" == "force" || ( "$is_pkg_manager_command" == true && "$pkg_manager_permission" == true ) ]]; then
        log sudo "${command[@]}"
        return
    fi
    
    error_output=$("${command[@]}" 2>&1)
    exit_code=$?

    if needs_sudo "$exit_code" "$error_output"; then
        handle_sudo_request "${command[@]}"
    fi
}

# Function to detect OS of machine
detect_os_version() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if [ -n "$ID" ] && [ -n "$VERSION_ID" ]; then
            echo "$ID-$VERSION_ID"
            return
        fi
    fi

    if command -v lsb_release > /dev/null 2>&1; then
        version=$(lsb_release -sr | cut -d. -f1)
        echo "$(lsb_release -si)-$version"
        return
    fi

    if [ -f /etc/lsb-release ]; then
        . /etc/lsb-release
        version=$(echo "$DISTRIB_RELEASE" | cut -d. -f1)
        echo "${DISTRIB_ID}-$version"
        return
    fi

    if [ -f /etc/debian_version ]; then
        version=$(cut -d. -f1 < /etc/debian_version)
        echo "debian-$version"
        return
    fi

    if [ -f /etc/redhat-release ]; then
        version=$(sed 's/.*release \([0-9]*\).*/\1/' < /etc/redhat-release)
        echo "$(sed 's/release [0-9]*.*//' < /etc/redhat-release)$version"
        return
    fi

    log_message "Error: Unable to detect OS version."
    exit 1
}

# Function to detect the package manager for the OS
detect_package_manager() {
    if command -v apt-get > /dev/null 2>&1; then
        echo "apt-get"
    elif command -v yum > /dev/null 2>&1; then
        echo "yum"
    elif command -v dnf > /dev/null 2>&1; then
        echo "dnf"
    elif command -v pacman > /dev/null 2>&1; then
        echo "pacman"
    elif command -v zypper > /dev/null 2>&1; then
        echo "zypper"
    else
        log_message "Error: No compatible package manager found. Exiting."
        exit 1
    fi
}

# Function to update the package manager
update_package_manager() {
    case $pkg_manager in
        apt-get) sudo_wrapper apt-get update -qq ;;
        yum) sudo_wrapper yum check-update -q ;;
        dnf) sudo_wrapper dnf check-update -q ;;
        pacman) sudo_wrapper pacman -Sy --noconfirm ;;
        zypper) sudo_wrapper zypper refresh ;;
        *) log_message "Error: No compatible package manager found."; exit 1 ;;
    esac
}

# Function to install packages using the package manager
install_packages() {
    local packages=("$@")
    
    for package in "${packages[@]}"; do
        case $pkg_manager in
            apt-get) sudo_wrapper apt-get install -y -qq "$package" || log_message "Warning: Package $package not found, skipping." ;;
            yum) sudo_wrapper yum install -y -q "$package" || log_message "Warning: Package $package not found, skipping." ;;
            dnf) sudo_wrapper dnf install -y -q "$package" || log_message "Warning: Package $package not found, skipping." ;;
            pacman) sudo_wrapper pacman -Sy --noconfirm "$package" || log_message "Warning: Package $package not found, skipping." ;;
            zypper) sudo_wrapper zypper install -y "$package" || log_message "Warning: Package $package not found, skipping." ;;
            *) log_message "Error: No compatible package manager found."; exit 1 ;;
        esac
    done
}

# Function to install different types of dependencies
install_dependencies() {
    local dep_type=$1
    local dependencies=()

    case $pkg_manager in
        apt-get)
            script_deps=(git curl jq)
            psychopy_deps=(libgtk-3-dev libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libxcb-xinerama0 libegl1-mesa-dev libsdl2-dev libglu1-mesa-dev libusb-1.0-0-dev portaudio19-dev libasound2-dev libxcb-cursor0 libxkbcommon-x11-0)
            python_build_deps=(build-essential libssl-dev zlib1g-dev libsqlite3-dev libffi-dev libbz2-dev libreadline-dev xz-utils make)
            wxpython_deps=(libjpeg-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x freeglut3-dev libpng-dev libtiff-dev libnotify-dev libsm-dev libgtk2.0-dev g++ make libglib2.0-dev)
            python_with_venv=(python3 python3-venv python3-pip python3-dev)
            ;;
        yum|dnf)
            script_deps=(git curl jq)
            psychopy_deps=(gtk3-devel webkit2gtk3-devel libxcb-xinerama mesa-libEGL-devel SDL2-devel mesa-libGLU-devel libusb1-devel portaudio-devel alsa-lib-devel)
            python_build_deps=(gcc openssl-devel bzip2-devel libffi-devel zlib-devel sqlite-devel readline-devel xz-devel make)
            wxpython_deps=(libjpeg-devel libpng-devel libSM-devel gcc-c++ gstreamer1-plugins-base gstreamer1-devel freeglut-devel libjpeg-turbo-devel libpng-devel libtiff-devel libnotify-devel gtk2-devel make glib2-devel)
            python_with_venv=(python3 python3-venv python3-pip python3-devel)
            ;;
        pacman)
            script_deps=(git curl jq)
            psychopy_deps=(gtk3 webkit2gtk libxcb mesa sdl2 glu libusb portaudio alsa-lib)
            python_build_deps=(base-devel openssl zlib sqlite libffi bzip2 readline xz make)
            wxpython_deps=(libjpeg libpng libsm mesa gstreamer gstreamer-base freeglut libtiff libnotify gtk2 gcc make glib2)
            python_with_venv=(python python-virtualenv python-pip)
            ;;
        zypper)
            script_deps=(git curl jq)
            psychopy_deps=(gtk3-devel libxcb-xinerama0 libSDL2-devel libusb-1_0-devel portaudio-devel alsa-devel)
            python_build_deps=(gcc libopenssl-devel zlib-devel sqlite3-devel libffi-devel bzip2-devel readline-devel xz-devel make)
            wxpython_deps=(libpng16-devel gstreamer-plugins-base freeglut-devel libnotify-devel libSM-devel gtk2-devel gcc-c++ make glib2-devel)
            python_with_venv=(python3 python3-virtualenv python3-pip python3-devel)
            ;;
        *)
            log_message "Error: No compatible package manager found."; exit 1
            ;;
    esac

    case $dep_type in
        script_deps) dependencies=("${script_deps[@]}") ;;
        python_build_deps) dependencies=("${python_build_deps[@]}") ;;
        psychopy_deps) dependencies=("${psychopy_deps[@]}") ;;
        wxpython_deps) dependencies=("${wxpython_deps[@]}") ;;
        python_with_venv) dependencies=("${python_with_venv[@]}") ;;
        *) log_message "Error: Invalid dependency type specified."; exit 1 ;;
    esac

    install_packages "${dependencies[@]}"
}

# Function to check if python version is available in package manager
check_python_pkg_manager() {
    local available_version
    
    case $pkg_manager in
        apt-get)
            available_version=$(apt-cache policy python3 | grep -m 1 "Candidate:" | awk '{print $2}' | cut -d'.' -f1,2)
            ;;
        yum)
            available_version=$(yum info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
            ;;
        dnf)
            available_version=$(dnf info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
            ;;
        pacman)
            available_version=$(pacman -Si python 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
            ;;
        zypper)
            available_version=$(zypper info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
            ;;
        *)
            log_message "Error: No compatible package manager found."; exit 1
            ;;
    esac

    if [ "$available_version" == "$python_version" ]; then
        return 0  
    else
        log_message "Warning: Python $python_version not available in $pkg_manager."
        return 1 
    fi
}

# Function to compare version numbers
version_greater_than() {
    if [[ "$1" =~ ^[0-9]+(\.[0-9]+)*$ ]] && [[ "$2" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
        [ "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1" ]
    else
        return 1
    fi
}

# Function to get the latest version of a package from PyPI
get_latest_pypi_version() {
    local package_name=$1
    local latest_version
    latest_version=$(curl -s "https://pypi.org/pypi/${package_name}/json" | jq -r .info.version)
    if [ -z "$latest_version" ]; then
        log_message "Error: Unable to fetch the latest version for package ${package_name}. Exiting."
        exit 1
    fi
    echo "$latest_version"
}

# Function to check if a specific version of a package exists on PyPI
check_pypi_for_version() {
    local package=$1
    local version=$2
    if ! curl -s "https://pypi.org/pypi/${package}/${version}/json" | jq -e .info.version > /dev/null; then
        log_message "Error: ${package} version ${version} does not exist. Exiting."
        exit 1
    fi
}

# Function to check if python is in path and pip and venv are installed
check_python_env() {
    local python_cmd="$1"
    if ! command -v "$python_cmd" > /dev/null 2>&1; then
        log_message "Error: $python_cmd not found. Exiting."
        exit 1
    fi

    if ! "$python_cmd" -m venv --help > /dev/null 2>&1; then
        log_message "Error: $python_cmd found, but venv module is not available. Exiting."
        exit 1
    fi

    if ! "$python_cmd" -m pip --version > /dev/null 2>&1; then
        log_message "Error: $python_cmd found, but pip is not installed. Exiting."
        exit 1
    fi
}

# Function to build Python from source
build_python() {
    local official_base_url latest_patch_version official_url temp_file temp_dir
    log_message "Info: Building Python ${python_version} from source this might take a while ..."
    official_base_url="https://www.python.org/ftp/python/"
    
    latest_patch_version=$(curl -s "${official_base_url}" | grep -oP "${python_version}\.[0-9]+/" | sort -V | tail -n 1 | sed 's:/$::')

    official_url="${official_base_url}${latest_patch_version}/Python-${latest_patch_version}.tgz"
    temp_file="Python-${latest_patch_version}.tgz"
    temp_dir="Python-${latest_patch_version}_temp"
    
    if ! curl -L -o "${temp_file}" "${official_url}"; then
        log_message "Error: Failed to download Python-${latest_patch_version} from python.org"
        exit 1
    fi

    mkdir -p "${temp_dir}" || { log_message "Error: Failed to create temp directory."; exit 1; }

    if ! tar -xf "${temp_file}" -C "${temp_dir}"; then
        log_message "Error: Failed to extract ${temp_file}."
        exit 1
    fi

    cd "${temp_dir}/Python-${latest_patch_version}" || { log_message "Error: Failed to change directory."; exit 1; }
    log ./configure --enable-optimizations --with-ensurepip=install --prefix=/usr/local/psychopy_python
    log make -j "$(nproc)"
    sudo_wrapper make altinstall
    cd "${psychopy_dir}" || { log_message "Error: Failed to return to psychopy directory."; exit 1; }

    sudo_wrapper rm -rf "${temp_dir}" "${temp_file}"
    return 0
}

# Function to download prebuilt Python from GitHub release
python_github_install() {
    local asset_name api_url assets_json temp_file temp_dir github_download_url python_version_pattern

    api_url="https://api.github.com/repos/wieluk/psychopy_linux_installer/releases/tags/v${script_version}"
    assets_json=$(curl -s "$api_url")

    if echo "$assets_json" | grep -q '"message": "Not Found"'; then
        log_message "Warning: Release v${script_version} not found on GitHub."
        return 1
    fi

    if [ -z "$assets_json" ]; then
        log_message "Warning: Empty response from GitHub API."
        return 1
    fi

    python_version_pattern="python-${python_version}\.[0-9]+-${processor_structure}-${os_version}\.tar\.gz"
    asset_name=$(echo "$assets_json" | jq -r '.assets[].name' | grep -E "$python_version_pattern" | sort -V | tail -n 1)

    if [ -z "$asset_name" ]; then
        log_message "Warning: No matching Python version found in release v${script_version} for Python ${python_version}."
        return 1
    fi

    github_download_url=$(echo "$assets_json" | jq -r --arg name "$asset_name" '.assets[] | select(.name == $name) | .browser_download_url')

    if [ -z "$github_download_url" ]; then
        log_message "Warning: Could not find download URL for asset $asset_name."
        return 1
    fi

    log_message "Info: Downloading $asset_name from GitHub."
    if curl -L -o "$asset_name" "$github_download_url"; then
        log_message "Info: Successfully downloaded ${asset_name} from GitHub release v${script_version}. Making an altinstall ..."
        temp_dir="${asset_name%.tar.gz}_temp"
        mkdir -p "$temp_dir" || { log_message "Error: Failed to create temp directory."; return 1; }

        if tar -xf "$asset_name" -C "$temp_dir"; then
            cd "$temp_dir" || { log_message "Error: Failed to change directory."; return 1; }
            sudo_wrapper make altinstall
            cd "${psychopy_dir}" || { log_message "Error: Failed to return to psychopy directory."; return 1; }
            sudo_wrapper rm -rf "$temp_dir" "$asset_name"
            return 0
        else
            log_message "Error: Failed to extract $asset_name."
            sudo_wrapper rm -rf "$temp_dir"
            return 1
        fi
    else
        log_message "Warning: Failed to download from GitHub release."
        return 1
    fi
}

# Function to build wxPython from source
build_wxpython() {
    log_message "Info: Installing wxPython build dependencies. This might take a while ..."
    install_dependencies wxpython_deps

    log_message "Info: Building wxPython $wxpython_version from source. This might take a while ..."
    if pip install --no-binary=:all: "wxpython==$wxpython_version"; then
        log_message "Info: Successfully built wxPython from source."
    else
        log_message "Error: Building wxPython from source failed."
        exit 1
    fi
}

# Function install wxPython using pip without building
wxpython_pip_install() {
    if log pip install --only-binary=:all: "wxpython==$wxpython_version"; then
        log_message "Info: Successfully installed wxPython version $wxpython_version using a pip wheel."
        return 0
    else
        return 1
    fi
}

# Function to install wxPython from wheel URL
wxpython_wheelurl_install() {
    local wheel_dir html wheels latest_wheel wheel_url wheel_file
    local base_url="https://extras.wxpython.org/wxPython4/extras/linux/gtk3/"
    wheel_dir="${base_url}${os_version}/"
    html=$(curl -s "$wheel_dir")
    wheels=$(echo "$html" | grep -oP 'href="\K[^"]*' | grep -E "${wxpython_version}.*${python_version}.*${processor_structure}.*\.whl" | grep -v ".asc" | sort)

    if [ -z "$wheels" ]; then
        log_message "Warning: No matching wxPython wheel found for ${wxpython_version}, ${os_version}, Python ${python_version}, and ${processor_structure} on extras.wxpython.org."
        return 1
    fi

    latest_wheel=$(echo "$wheels" | tail -n 1)
    wheel_url="${wheel_dir}${latest_wheel}"
    wheel_file=$(basename "$wheel_url")

    if log curl -s -O "$wheel_url"; then
        log_message "Info: Download from extras.wxpython.org successful. Installing wxPython from $wheel_file..."
        if log pip install "$wheel_file"; then
            log_message "Info: Installed wxPython from $wheel_file"
            rm "$wheel_file"
            return 0
        else
            log_message "Warning: Installing wxPython from $wheel_file failed."
            rm "$wheel_file"
            return 1
        fi
    else
        log_message "Warning: Downloading $wheel_url failed."
        return 1
    fi
}

# Function to install wxPython from GitHub release
wxpython_github_install() {
    local api_url assets_json wheel_name renamed_wheel download_url python_version_major_minor

    api_url="https://api.github.com/repos/wieluk/psychopy_linux_installer/releases/tags/v${script_version}"

    assets_json=$(curl -s "$api_url")
    if echo "$assets_json" | grep -q '"message": "Not Found"'; then
        log_message "Warning: Release v${script_version} not found on GitHub."
        return 1
    fi

    if [ -z "$assets_json" ]; then
        log_message "Warning: Empty response from GitHub API."
        return 1
    fi
    
    python_version_major_minor=$(echo "${python_version}" | awk -F. '{printf "%s%s", $1, $2}')
    wheel_name="wxPython-${wxpython_version}-cp${python_version_major_minor}-cp${python_version_major_minor}-${processor_structure}-${os_version}.whl"

    download_url=$(echo "$assets_json" | jq -r --arg name "$wheel_name" '.assets[] | select(.name == $name) | .browser_download_url')

    if [ -z "$download_url" ]; then
        log_message "Warning: No matching wxPython wheel found in release v${script_version} for wxPython ${wxpython_version}."
        return 1
    fi

    log_message "Info: Downloading $wheel_name from GitHub."
    if curl -L -o "$wheel_name" "$download_url"; then
        log_message "Info: Successfully downloaded wxPython wheel from GitHub release. Installing wxPython from $wheel_name..."
        renamed_wheel="${wheel_name%-"${os_version}".whl}.whl"
        mv "$wheel_name" "$renamed_wheel"
        log_message "Info: Download from GitHub successful. Installing wxPython from $renamed_wheel"
        if log pip install "$renamed_wheel"; then
            log_message "Info: Installed wxPython from $renamed_wheel"
            rm "$renamed_wheel"
            return 0
        else
            log_message "Warning: Installing wxPython from $renamed_wheel failed."
            rm "$renamed_wheel"
            return 1
        fi
    else
        log_message "Warning: Downloading $wheel_name failed."
        return 1
    fi
}


# Function to create a desktop shortcut file
create_desktop_shortcut() {
    local desktop_shortcut
    local desktop_dir="${HOME}/.local/share/applications/"
    local psychopy_exec="${psychopy_dir}/bin/psychopy"
    local resources_dir="${psychopy_dir}/Resources"
    
    desktop_shortcut="$(xdg-user-dir DESKTOP)"
    
    local shortcuts=(
        "--no-splash" "PsychoPy (v${psychopy_version}) Python(v${python_version})" "psychopy.png"
        "--builder --no-splash" "PsychoPy Builder (v${psychopy_version}) Python(v${python_version})" "builder.png"
        "--coder --no-splash" "PsychoPy Coder (v${psychopy_version}) Python(v${python_version})" "coder.png"
    )

    if [ ! -d "$desktop_shortcut" ]; then
        log_message "Warning: Desktop directory $desktop_shortcut does not exist. Skipping desktop shortcut creation."
        return
    fi

    mkdir -p "${resources_dir}"

    for ((i=0; i<${#shortcuts[@]}; i+=3)); do
        local exec_args="${shortcuts[i]}"
        local pretty_name="${shortcuts[i+1]}"
        local icon_file="${shortcuts[i+2]}"
        local icon_url="https://raw.githubusercontent.com/wieluk/psychopy_linux_installer/main/Resources/${icon_file}"
        local desktop_file="${desktop_shortcut}/${pretty_name}.desktop"
        local icon_path="${resources_dir}/${icon_file}"

        if curl --output /dev/null --silent --head --fail "${icon_url}"; then
            log curl -s -o "${icon_path}" "${icon_url}"
        else
            log_message "Warning: Icon file ${icon_url} not found, skipping..."
        fi

        local icon_line=""
        if [ -f "$icon_path" ]; then
            icon_line="Icon=${icon_path}"
        fi

        local desktop_content="[Desktop Entry]
Version=1.0
Name=${pretty_name}
Comment=Run PsychoPy version ${psychopy_version} with ${exec_args}
Exec=${psychopy_exec} ${exec_args}
${icon_line}
Terminal=false
Type=Application
Categories=Education;Science;"

        sh -c "echo '$desktop_content' > '$desktop_file'"
        sudo_wrapper chmod +x "$desktop_file"
        sudo_wrapper chown "$USER" "$desktop_file"
        gio set "$desktop_file" metadata::trusted true
        sudo_wrapper ln -sf "$desktop_file" "${desktop_dir}${pretty_name}.desktop"
    done
}

# Function to create add PsychoPy to system path
add_psychopy_to_path() {
    local shell_name
    local bin_dir="${psychopy_dir}/.bin"
    local target_bin="${bin_dir}/psychopy_${psychopy_version}_py${python_version}"

    shell_name=$(basename "$SHELL")
    mkdir -p "$bin_dir"
    ln -sf "${psychopy_dir}/bin/psychopy" "$target_bin"

    local config_file=""
    local path_line=""

    case $shell_name in
        bash)
            config_file="$HOME/.bashrc"
            path_line="export PATH=\"${bin_dir}:\$PATH\""
            ;;
        zsh)
            config_file="$HOME/.zshrc"
            path_line="export PATH=\"${bin_dir}:\$PATH\""
            ;;
        fish)
            config_file="$HOME/.config/fish/config.fish"
            path_line="set -gx PATH \"${bin_dir}\" \$PATH"
            ;;
        csh|tcsh)
            config_file="$HOME/.${shell_name}rc"
            path_line="setenv PATH ${bin_dir}:\$PATH"
            ;;
        *)
            log_message "Warning: Unsupported shell: $shell_name; PsychoPy not added to path"
            ;;
    esac

    if ! grep -Fxq "$path_line" "$config_file"; then
        sh -c "echo '$path_line' >> \"$config_file\""
        log_message "Info: PsychoPy path added to $config_file"
    else
        log_message "Info: PsychoPy path already exists in $config_file"
    fi
}

main() {
    psychopy_version="latest"
    python_version="3.10"
    wxpython_version="4.2.2"
    build_python=false
    build_wx=false
    install_dir="$HOME"
    no_versioned_install_dir=false
    install_dir_set_by_user=false
    additional_packages=""
    sudo_mode="ask"
    pkg_manager_permission=false
    disable_shortcut=false
    disable_path=false
    force_overwrite=false
    verbose=false

    for arg in "$@"; do
        case $arg in
            --psychopy-version=*)
                psychopy_version="${arg#*=}"
                ;;
            --python-version=*)
                python_version="${arg#*=}"
                if [[ ! $python_version =~ ^3\.(8|9|10)$ ]]; then
                    echo "Error: Invalid Python version specified. Only versions 3.8, 3.9, or 3.10 are allowed."
                    exit 1
                fi
                ;;
            --wxpython-version=*)
                wxpython_version="${arg#*=}"
                ;;
            --build=*)
                build_arg="${arg#*=}"
                case $build_arg in
                    python)
                        build_python=true
                        ;;
                    wxpython)
                        build_wx=true
                        ;;
                    both)
                        build_python=true
                        build_wx=true
                        ;;
                    *)
                        echo "Error: Invalid option for --build: $build_arg"
                        show_help
                        exit 1
                        ;;
                esac
                ;;
            --install-dir=*)
                install_dir="${arg#*=}"
                install_dir_set_by_user=true
                ;;
            --no-versioned-install-dir)
                if [ "$install_dir_set_by_user" = false ]; then
                    echo "Error: --no-versioned-install-dir cannot be used without setting --install_dir."
                    exit 1
                fi
                no_versioned_install_dir=true
                ;;
            --additional-packages=*)
                additional_packages="${arg#*=}"
                ;;
            --sudo-mode=*)
                sudo_mode="${arg#*=}"
                if [[ "$sudo_mode" != "ask" && "$sudo_mode" != "continue" && "$sudo_mode" != "auto" && "$sudo_mode" != "error"  && "$sudo_mode" != "force" ]]; then
                    echo "Error: Invalid value for --sudo_mode. Valid options are 'ask', 'continue', 'auto', 'error' or 'force'."
                    exit 1
                fi
                ;;
            --disable-shortcut)
                disable_shortcut=true
                ;;
            --disable-path)
                disable_path=true
                ;;
            -f|--force)
                force_overwrite=true
                ;;
            -v|--verbose)
                verbose=true
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                echo "Error: Unknown option: $arg"
                show_help
                exit 1
                ;;
        esac
    done

    # Detect OS version and architecture
    os_version=$(detect_os_version | tr '[:upper:]' '[:lower:]')
    processor_structure=$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m)
    script_version=$(grep -m 1 'Version:' "$0" | sed 's/[^0-9.]//g')
    log_message "Info: Initiating PsychoPy(${psychopy_version}) installation using psychopy_linux_installer v${script_version} on ${os_version} (${processor_structure})."

    # Detect package manager
    pkg_manager=$(detect_package_manager)

    # Update package manager
    log_message "Info: Updating ${pkg_manager} package manager."
    update_package_manager "$pkg_manager"

    # Install basic dependencies
    log_message "Info: Installing git, curl, and jq."
    install_dependencies script_deps

    # Determine PsychoPy version to install
    if [ "$psychopy_version" == "latest" ]; then
        psychopy_version=$(get_latest_pypi_version "psychopy")
    elif [ "$psychopy_version" != "git" ]; then
        check_pypi_for_version psychopy "${psychopy_version}"
    fi

    # Install PsychoPy dependencies
    log_message "Info: Installing PsychoPy dependencies. This might take a while ..."
    install_dependencies psychopy_deps

    # Set up PsychoPy installation directory
    if [ "$no_versioned_install_dir" = true ]; then
        psychopy_dir="${install_dir}"
    else
        psychopy_dir="${install_dir}/psychopy_${psychopy_version}_py${python_version}"
    fi

    if [ -d "${psychopy_dir}" ]; then
        if [ "$force_overwrite" = true ]; then
            log_message "Info: Directory ${psychopy_dir} already exists. Overwriting ..."
            sudo_wrapper rm -rf "${psychopy_dir}"
            sudo_wrapper mkdir -p "${psychopy_dir}"
        else
            log_message "Error: Directory ${psychopy_dir} already exists. Use the --force flag to overwrite. Exiting."
            exit 1
        fi
    else
        log_message "Info: Creating PsychoPy directory at ${psychopy_dir} ..."
        sudo_wrapper mkdir -p "${psychopy_dir}"
    fi

    [ -w "${psychopy_dir}" ] || sudo_wrapper chown "$USER" "${psychopy_dir}"

    if ! [ -w "${psychopy_dir}" ] || ! cd "${psychopy_dir}"; then
        log_message "Error: Failed to access or change directory to ${psychopy_dir}. Exiting."
        exit 1
    fi
    
    # Install python and create vnev
    if [ "$build_python" = true ] || ! check_python_pkg_manager; then
        if [ "$build_python" = true ]; then
            log_message "Info: Installing python build dependencies ..."
            install_dependencies python_build_deps
            build_python
        else
            if [ -x "/usr/local/psychopy_python/bin/python${python_version}" ]; then
                log_message "Info: Python version ${python_version} is already installed in /usr/local/psychopy_python. Skipping installation."
            else
                log_message "Info: Installing python build dependencies ..."
                install_dependencies python_build_deps
                if python_github_install; then
                    :
                else   
                    build_python
                fi
            fi
        fi

        if [ ! -x "/usr/local/psychopy_python/bin/python${python_version}" ]; then
            log_message "Error: python${python_version} not found in /usr/local/psychopy_python. Something went wrong while installing/building. Try --build=python and --verbose as arguments."
            exit 1
        fi
        export PATH=/usr/local/psychopy_python/bin:$PATH
        /usr/local/psychopy_python/bin/python"${python_version}" -m venv "${psychopy_dir}"
    else
        log_message "Info: Python${python_version} can be installed via package manager. Installing ..."
        install_dependencies python_with_venv
        check_python_env "python${python_version}"
        python"${python_version}" -m venv "${psychopy_dir}"
    fi

    # Activate venv
    log_message "Info: Succesfully created Python${python_version} venv in ${psychopy_dir} ... Activating."
    log source "${psychopy_dir}/bin/activate"
    check_python_env "python"

    # Upgrade pip and install required Python packages
    log_message "Info: Upgrading pip, distro, sip, six, psychtoolbox and attrdict ..."
    log pip install -U pip distro sip six psychtoolbox attrdict

    # Install numpy<2 if PsychoPy version is less than 2024.2.0
    if version_greater_than "2024.2.0" "$psychopy_version"; then
        log_message "Info: PsychoPy version < 2024.2.0, installing numpy<2"
        log pip install "numpy<2"
    fi

    # Determine wxPython version and install it
    if [ "$wxpython_version" = "latest" ]; then
        wxpython_version=$(get_latest_pypi_version "wxPython")
    elif [ "$wxpython_version" != "git" ]; then
        check_pypi_for_version wxpython "${wxpython_version}"
    fi

    if [ "$wxpython_version" = "git" ]; then
        log_message "Info: Installing wxPython build dependencies. This might take a while ..."
        install_dependencies wxpython_deps
        log_message "Info: Building wxPython from git. This might take a while ..."
        log pip install git+https://github.com/wxWidgets/Phoenix
    elif [ "$build_wx" = true ]; then
        build_wxpython
    else
        if wxpython_pip_install; then
            :
        elif wxpython_wheelurl_install; then
            :
        elif wxpython_github_install; then
            :
        else
            build_wxpython
        fi
    fi

    if ! pip show wxPython &> /dev/null; then
        log_message "Error: wxPython is not installed. Something went wrong during the installation. Use --verbose and maybe --build=wxpython flags."
        exit 1
    fi

    # Install PsychoPy
    log_message "Info: Installing PsychoPy version ${psychopy_version}"
    if [ "$psychopy_version" == "git" ]; then
        log pip install git+https://github.com/psychopy/psychopy.git@dev
    else
        log pip install psychopy=="${psychopy_version}"
    fi

    if ! pip show psychopy &> /dev/null; then
        log_message "Error: PsychoPy is not installed successfully. Something went wrong during the installation. Use the --verbose flag."
        exit 1
    fi

    # Install additional packages if specified
    if [ -n "$additional_packages" ]; then
        log_message "Info: Installing additional packages..."
        IFS=',' read -ra PACKAGES <<< "$additional_packages"
        for package in "${PACKAGES[@]}"; do
            log_message "Info: Installing $package..."
            if log pip install "$package"; then
                installed_version=$(pip show "${package%%=*}" | grep Version | cut -d' ' -f2)
                log_message "Info: ${package%%=*} version $installed_version installed successfully."
            else
                log_message "Warning: Failed to install $package. Skipping."
            fi
        done
    fi

    # Deactivate virtual environment
    deactivate

    # Add user to the 'psychopy' group and set security limits
    log_message "Info: Adding ${USER} to psychopy group and setting security limits in /etc/security/limits.d/99-psychopylimits.conf."
    sudo_wrapper groupadd --force psychopy
    sudo_wrapper usermod -a -G psychopy "$USER"
    sudo_wrapper sh -c 'echo "@psychopy - nice -20\n@psychopy - rtprio 50\n@psychopy - memlock unlimited" > /etc/security/limits.d/99-psychopylimits.conf'

    # Create desktop shortcut
    if [ "$disable_shortcut" = false ]; then
        create_desktop_shortcut
    else
        log_message "Info: Desktop shortcut creation disabled by user."
    fi

    # Add PsychoPy to PATH
    if [ "$disable_path" = false ]; then
        add_psychopy_to_path
    else
        log_message "Info: Adding PsychoPy to system path disabled by user."
    fi

    echo
    log_message "PsychoPy installation complete!"
    echo
    echo "Please reboot to apply security limits and to refresh system path."
    echo
    echo "To start PsychoPy from terminal, use:"
    echo "psychopy_${psychopy_version}_py${python_version}"
    echo
    echo "If PsychoPy is not added to system path,use the absolute path:"
    echo "${psychopy_dir}/bin/psychopy"
}

main "$@"