FROM opensuse/leap:latest

# Install dependencies
RUN zypper refresh && \
    zypper install -y \
    python3-pip \
    ShellCheck \
    curl \
    git \
    sudo

# Install Python packages
RUN pip install bashate codespell
