FROM archlinux:latest

# Install dependencies
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
    python-pip \
    shellcheck \
    curl \
    git \
    sudo

# Install Python packages
RUN pip install bashate codespell --break-system-packages
