FROM fedora:latest

# Install dependencies
RUN dnf update -y && \
    dnf install -y \
    python3-pip \
    ShellCheck \
    curl \
    git \
    sudo

# Install Python packages
RUN pip install bashate codespell --break-system-packages
