name: Run PsychoPy Installer

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # This triggers the workflow on pull requests to the main branch

jobs:
  run-installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./psychopy_linux_installer.sh

    - name: Run PsychoPy Linux Installer
      run: ./psychopy_linux_installer.sh
