name: Run PsychoPy Installer on Multiple OS

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on
      - testing

jobs:
  run-installer:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./psychopy_linux_installer.sh

    - name: Run PsychoPy Linux Installer
      run: sudo ./psychopy_linux_installer.sh | tee psychopy_install_output.log
      shell: bash

    - name: Extract PsychoPy start command
      id: extract-command
      run: |
        PSYCHOPY_COMMAND=$(tail -n 1 psychopy_install_output.log | grep -o 'psychopy_v.*_py_v.*')
        echo "PsychoPy start command: $PSYCHOPY_COMMAND"
        echo "PSYCHOPY_COMMAND=$PSYCHOPY_COMMAND" >> $GITHUB_ENV
        echo "psychopy_command=$PSYCHOPY_COMMAND" >> $GITHUB_OUTPUT

    - name: Verify PsychoPy installation with --help
      run: ${{ env.PSYCHOPY_COMMAND }} -h
      shell: bash

    - name: Verify PsychoPy installation with --version
      run: ${{ env.PSYCHOPY_COMMAND }} -v
      shell: bash

    - name: Run a simple PsychoPy script in headless mode
      run: |
        echo "print('Hello from PsychoPy script')" > test_script.py
        ${{ env.PSYCHOPY_COMMAND }} -x test_script.py
      shell: bash

    - name: Run PsychoPy GUI (optional, does not affect overall success)
      run: ${{ env.PSYCHOPY_COMMAND }}
      shell: bash
      continue-on-error: true