name: Run PsychoPy Installer on Multiple OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-installer:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./psychopy_linux_installer.sh

    - name: Run PsychoPy Linux Installer
      id: install_psychopy
      run: |
        output=$(sudo ./psychopy_linux_installer.sh)
        echo "$output"
        install_path=$(echo "$output" | grep -oP '(?<=PsychoPy installed at: ).*')
        echo "install_path=$install_path" >> $GITHUB_ENV
      shell: bash

    - name: Verify Installation
      run: |
        if [ ! -d "$install_path" ]; then
          echo "PsychoPy installation directory not found!"
          exit 1
        fi

    - name: Check PsychoPy Version
      run: |
        $install_path/bin/psychopy --version

    - name: Run PsychoPy Command Line Tests
      run: |
        $install_path --help
        $install_path --test
      shell: bash

    - name: Run PsychoPy Headless Test
      run: |
        xvfb-run $install_path --test
      shell: bash

    - name: Run PsychoPy
      run: |
        $install_path
      shell: bash
