name: Run PsychoPy Installer on Multiple OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-installer:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./psychopy_linux_installer.sh

    - name: Run PsychoPy Linux Installer
      id: install_psychopy
      run: |
        set -o pipefail
        output_file=installer_output.txt
        sudo ./psychopy_linux_installer.sh > $output_file 2>&1
        cat $output_file
        install_path=$(grep -oP '(?<=PsychoPy installed at: ).*' $output_file)
        echo "install_path=$install_path" >> $GITHUB_ENV
      shell: bash

    - name: Verify Installation
      run: |
        echo "Installation path: ${{ env.install_path }}"
        if [ ! -d "${{ env.install_path }}" ]; then
          echo "PsychoPy installation directory not found!"
          exit 1
        fi

    - name: Check PsychoPy Version
      run: ${{ env.install_path }}/bin/psychopy --version

    - name: Run PsychoPy Command Line Tests
      run: |
        ${{ env.install_path }}/bin/psychopy --help
        ${{ env.install_path }}/bin/psychopy --test
      shell: bash

    - name: Run PsychoPy Headless Test
      run: |
        xvfb-run ${{ env.install_path }}/bin/psychopy --test
      shell: bash

    - name: Run PsychoPy
      run: ${{ env.install_path }}/bin/psychopy
      shell: bash
