name: Run PsychoPy Installer on Multiple OS

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # This triggers the workflow on pull requests to the main branch

jobs:
  run-installer:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./psychopy_linux_installer.sh

    - name: Run PsychoPy Linux Installer
      run: sudo ./psychopy_linux_installer.sh
      shell: bash
