name: PsychoPy Linux Installer main merge workflow

on:
  push:
    branches: [main]
    paths:
      - psychopy_linux_installer
      - .github/workflows/**
      - .github/PsychoPy_tests/**
  workflow_dispatch:

jobs:
  # Initial syntax check
  syntax-check:
    uses: ./.github/workflows/reusable_syntax_check.yaml

  # Create a release if it does not exist
  create-release:
    needs: syntax-check
    uses: ./.github/workflows/reusable_release.yaml

  # Build binaries and upload to release
  build-binaries:
    needs: create-release
    uses: ./.github/workflows/reusable_build.yaml

  # Test installation without build
  test-installation:
    needs: build-binaries
    if: success()
    uses: ./.github/workflows/reusable_test.yaml

  # Test installation with build
  test-installation-build:
    needs: test-installation
    if: success()
    uses: ./.github/workflows/reusable_test.yaml
    with:
      build-mode: true
