name: Run quick test

on:
  push:
    paths:
      - psychopy_linux_installer
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: |
          sudo apt-get install -y shellcheck
          bash -n $GITHUB_WORKSPACE/psychopy_linux_installer
          shellcheck -e SC1017 -e SC1091 $GITHUB_WORKSPACE/psychopy_linux_installer
  
  run-installer:
    runs-on: ["${{ matrix.os }}"]
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        python_version: ['3.8', '3.9', '3.10']
        psychopy_version: ['latest', '2023.2.3', '2024.1.4']
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment and install
        env:
          PYTHON_VERSION: ${{ matrix.python_version }}
          PSYCHOPY_VERSION: ${{ matrix.psychopy_version }}
        run: |
          if [ "$PSYCHOPY_VERSION" == "latest" ]; then
            PSYCHOPY_VERSION=$(curl -s https://pypi.org/pypi/psychopy/json | jq -r .info.version)
          fi

          sudo chmod +x $GITHUB_WORKSPACE/psychopy_linux_installer
          sudo rm -rf /tmp_dir
          sudo mkdir /tmp_dir
          sudo chown -R $USER:$(id -gn $USER) /tmp_dir
          cp -rf $GITHUB_WORKSPACE/.github/PsychoPy_tests /tmp_dir/

          ARGS="--python-version=$PYTHON_VERSION --psychopy-version=$PSYCHOPY_VERSION --additional-packages=psychopy_bids,seedir --install-dir=/tmp_dir/psychopy --no-versioned-install-dir --force --sudo-mode=auto"
          $GITHUB_WORKSPACE/psychopy_linux_installer $ARGS

      - name: Verify PsychoPy installation and version
        id: verify-psychopy
        continue-on-error: true
        run: |
            if ! /tmp_dir/psychopy/bin/psychopy -h &> /dev/null; then
              echo "PsychoPy help command failed"
              exit 1
            fi
            
            if ! /tmp_dir/psychopy/bin/psychopy -v | grep -qE "PsychoPy3, version [0-9]+\.[0-9]+\.[0-9]+"; then
              echo "PsychoPy version check failed"
              exit 1
            fi
        
      - name: Run basic PsychoPy test
        id: psychopy-test
        continue-on-error: true
        run: |
            cd /tmp_dir/PsychoPy_tests
            /tmp_dir/psychopy/bin/python /tmp_dir/PsychoPy_tests/psychopy_test.py 2>&1 | tee /tmp_dir/PsychoPy_tests/psychopy_test.log
            set -e
            if ! tail -n 1 /tmp_dir/PsychoPy_tests/psychopy_test.log | grep -qE "Trial 3: Elapsed time .* seconds"; then
              echo "::error::PsychoPy test output verification failed"
              exit 1
            fi
  
      - name: Run extended PsychoPy Tests
        id: psychopy-test-extended
        continue-on-error: true
        run: |
            output=$(/tmp_dir/psychopy/bin/python /tmp_dir/PsychoPy_tests/psychopy_test_extended.py)
            tests=("Visual" "Keyboard" "Image" "Timing")
            for test in "${tests[@]}"; do
              if ! echo "$output" | grep -qE "${test} Test Passed"; then
                echo "::error::${test} Test Failed"
                exit 1
              fi
            done
            echo "All tests passed successfully."
  
      - name: Verify BIDS installation simple
        id: verify-bids
        continue-on-error: true
        run: |
            cd /tmp_dir/PsychoPy_tests/BIDS
            if ! /tmp_dir/psychopy/bin/python bids_test_simple.py; then
              echo "::error::BIDS simple test execution failed"
              exit 1
            fi
      
      - name: Verify BIDS installation exp_handler
        id: verify-bids-handler
        continue-on-error: true
        run: |
            cd /tmp_dir/PsychoPy_tests/BIDS
            if ! /tmp_dir/psychopy/bin/python bids_test_exp_handler.py; then
              echo "::error::BIDS exp_handler test execution failed"
              exit 1
            fi
      
      - name: Cleanup
        if: always()
        run: | 
          sudo rm -rf /tmp_dir ~/Desktop/* ~/.local/share/applications/*

